name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_ps3" -type f -delete
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB2DX-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          %SystemRoot%\System32\robocopy.exe "._ark" "._temp\_ark" *.milo_xbox /S /MOVE /XD "._temp\_ark" /NDL /NFL /NJH /NJS /R:0 >nul
          %SystemRoot%\System32\robocopy.exe "._ark" "._temp\_ark" *.png_xbox /S /MOVE /XD "._temp\_ark" /NDL /NFL /NJH /NJS /R:0 >nul
          %SystemRoot%\System32\robocopy.exe "._ark" "._temp\_ark" *.bmp_xbox /S /MOVE /XD "._temp\_ark" /NDL /NFL /NJH /NJS /R:0 >nul
          dependencies/windows/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5

      - name: Build PKG
        run: dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe dependencies/ta_pkg_repacker_tools/package.conf _build/ps3
      
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB2DX-PS3
          path: '*.pkg'
