name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_ps3" -type f -delete
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB2DX-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          dependencies/windows/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe dependencies/ta_pkg_repacker_tools/package.conf _build/ps3
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB2DX-PS3
          path: dependencies/ta_pkg_repacker_tools/UP0006-BLUS30147_00-RB2DXNITE0000000.pkg
